Spring pagination
fedaktaras/book-store-app pull request #5
Opened 2024-05-02 14:59 UTC by fedaktaras

2024-05-03 11:59 UTC, EduarfF approved these changes

2024-05-03 15:03 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-03 15:03 UTC, andrii-hoienko commented on pom.xml
> +        <relativePath/> <!-- lookup parent from repository -->
```suggestion
        <relativePath/>
```

2024-05-03 15:03 UTC, andrii-hoienko commented on pom.xml
> +        </dependency>
Please be consistent and use properties to define versions of dependencies

2024-05-07 13:04 UTC, andrii-hoienko approved these changes
Good job!

2024-05-07 15:39 UTC, merged