Spring security jwt
fedaktaras/book-store-app pull request #8
Opened 2024-05-14 14:42 UTC by fedaktaras

Implemented login to book store application.

2024-05-15 10:02 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-05-15 10:02 UTC, vovasalyha commented on pom.xml
> +            <version>0.12.5</version>
It's a good practice to extract versions to properties.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/java/com/example/bookstoreapp/dto/UserRegistrationRequestDto.java
> +    private String email;
Don't forget to validate a maximum size of text fields to avoid errors because of DB column size limitations.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/java/com/example/bookstoreapp/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.INTERNAL_SERVER_ERROR);
Why is `RegistrationException` a 500 status? It's a client exception so make it 4xx (400 or 409 in this case)

2024-05-15 10:02 UTC, vovasalyha commented on src/main/java/com/example/bookstoreapp/model/User.java
> +public class User implements UserDetails {
I suggest overriding equals and hashCode too.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/java/com/example/bookstoreapp/security/AuthenticationService.java
> +        SecurityContextHolder.getContext().setAuthentication(authentication);
I don't see a reason to set authentication context here. But if it's used somewhere you can leave it.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/java/com/example/bookstoreapp/security/JwtUtil.java
> +    private long expiration;
IMO it would be more consistent if you inject everything in a constructor and make this field final. But it's up to you.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/java/com/example/bookstoreapp/security/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
```suggestion
            return false;
```

2024-05-15 10:02 UTC, vovasalyha commented on src/main/resources/application.properties
> +jwt.secret=lskjqlsfjdcsdbgtkedsdfnxdfsdflkhglskglsasfdnauercnalajfcmlahfcmlasfcmwurc
It's better to store sensitive info in system properties and not pushing it to git.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/04-create-table-users-roles.yaml
> +                  name: user_id
Make user_id + role_id a composite PK to disallow duplicate entries.

2024-05-15 10:02 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/07-insert-ADMIN-to-id-1.yaml
> +                  valueComputed: "(SELECT id FROM roles WHERE role = 'ADMIN')"
Don't forget about empty lines.

2024-05-16 09:11 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/model/User.java
> +
```suggestion

```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/model/User.java
> +public class User implements UserDetails {
```suggestion
@EqualsAndHashCode
public class User implements UserDetails {
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/model/User.java
> +    )
```suggestion
    @ManyToMany(fetch = FetchType.EAGER)
    @ExcludeFromEqualsAndHashCode //annotation could have different name
    @JoinTable(
            name = "users_roles",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "roles_id")
    )
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/security/CustomUserDetailsService.java
> +        return user.orElseThrow(() -> new UsernameNotFoundException("Can't find user by email"));
```suggestion
        return user.orElseThrow(() -> new UsernameNotFoundException("Can't find user by username: USERNAME"));
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/security/CustomUserDetailsService.java
> +        return user.orElseThrow(() -> new UsernameNotFoundException("Can't find user by email"));
Could be inline

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please move to constants

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
Magic number

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring("Bearer ".length);
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/servive/impl/UserServiceImpl.java
> +        newUser.setRoles(Set.of(userRole));
Code duplication

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/servive/impl/UserServiceImpl.java
> +        newUser.setRoles(new HashSet<>(Collections.singletonList(userRole)));
```suggestion
        newUser.setRoles(Collections.singletonList(userRole));
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/servive/impl/UserServiceImpl.java
> +        }
move to separate method named checkIfUserExists or something like that

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/validator/FieldMatchValidator.java
> +public class FieldMatchValidator implements ConstraintValidator<FieldMatch, Object> {
These changes should be made in the scope of different pr, please prepare pr with only relevant changes

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/07-insert-ADMIN-to-id-1.yaml
```suggestion
      file: db/changelog/changes/07-insert-ADMIN-to-id-1.yaml
      
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/dto/UserLoginResponseDto.java
> +    }
```suggestion
@Data
public class UserLoginResponseDto {
    private String token;

    public UserLoginResponseDto(String token) {
        this.token = token;
    }
```
```suggestion
@Data
@AllArgsConstructor
public class UserLoginResponseDto {
    private String token;
```

2024-05-16 09:11 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapp/validator/FieldMatchValidator.java
> +                    || (firstObj != null && firstObj.equals(secondObj));
Is is possible to use Objects.equals?

2024-05-16 09:16 UTC, fedaktaras commented on src/main/java/com/example/bookstoreapp/model/User.java
> +public class User implements UserDetails {
> @EqualsAndHashCode

completely forgot about this anotation

2024-05-16 10:45 UTC, yevheniisynytsia approved these changes
Well done!

2024-05-16 10:45 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstoreapp/exception/CustomGlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleRuntimeException(Exception ex, WebRequest request) {
```suggestion
    public ResponseEntity<Object> handleException(Exception ex, WebRequest request) {
```

2024-05-16 10:45 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstoreapp/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", config = MapperConfig.class)
I believe `componentModel = "spring"` is already defined in your `MapperConfig`

2024-05-16 10:45 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +      id: 2
```suggestion
      id: 02
```
to be consistent

2024-05-20 15:09 UTC, merged